# Generated by Django 5.2.3 on 2025-07-16 13:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the data source', max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('csv_upload', 'CSV File Upload'), ('api_endpoint', 'API Endpoint'), ('real_time_feed', 'Real-time Data Feed')], help_text='Type of data source', max_length=20)),
                ('endpoint_url', models.URLField(blank=True, help_text='API endpoint URL (if applicable)', null=True)),
                ('api_key', models.CharField(blank=True, help_text='API key for authentication (if required)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this data source is currently active')),
                ('last_ingestion', models.DateTimeField(blank=True, help_text='Timestamp of last successful data ingestion', null=True)),
                ('ingestion_frequency_minutes', models.IntegerField(default=60, help_text='How often to ingest data (in minutes)', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(help_text='Unique identifier for the flight', max_length=50, unique=True)),
                ('aircraft_id', models.CharField(help_text='Aircraft registration or identifier', max_length=20)),
                ('timestamp', models.DateTimeField(help_text='Timestamp of the flight data point')),
                ('latitude', models.FloatField(help_text='Latitude coordinate in decimal degrees', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(help_text='Longitude coordinate in decimal degrees', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('altitude', models.IntegerField(help_text='Altitude in feet')),
                ('speed', models.FloatField(help_text='Ground speed in knots', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('heading', models.FloatField(help_text='Aircraft heading in degrees (0-360)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)])),
                ('origin', models.CharField(blank=True, help_text='Origin airport code (ICAO/IATA)', max_length=10, null=True)),
                ('destination', models.CharField(blank=True, help_text='Destination airport code (ICAO/IATA)', max_length=10, null=True)),
                ('route_points', models.JSONField(default=list, help_text='Array of route coordinates as [lat, lng] pairs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['flight_id'], name='flights_fli_flight__5aaf6d_idx'), models.Index(fields=['aircraft_id'], name='flights_fli_aircraf_ae386b_idx'), models.Index(fields=['timestamp'], name='flights_fli_timesta_204918_idx'), models.Index(fields=['origin', 'destination'], name='flights_fli_origin_f6559c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('route_deviation', 'Route Deviation'), ('speed_anomaly', 'Speed Anomaly'), ('altitude_anomaly', 'Altitude Anomaly'), ('temporal_anomaly', 'Temporal Pattern Anomaly'), ('combined', 'Combined Anomaly')], help_text='Type of anomaly detected', max_length=50)),
                ('confidence_score', models.FloatField(help_text='ML model confidence score (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when anomaly was detected')),
                ('ml_model_version', models.CharField(help_text='Version of the ML model used for detection', max_length=20)),
                ('anomaly_details', models.JSONField(default=dict, help_text='Additional details about the anomaly (features, thresholds, etc.)')),
                ('is_reviewed', models.BooleanField(default=False, help_text='Whether this anomaly has been reviewed by a human')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from human reviewer', null=True)),
                ('is_false_positive', models.BooleanField(default=False, help_text='Marked as false positive after review')),
                ('flight', models.ForeignKey(help_text='Associated flight record', on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_detections', to='flights.flight')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['anomaly_type'], name='flights_ano_anomaly_ed1f81_idx'), models.Index(fields=['confidence_score'], name='flights_ano_confide_b6e575_idx'), models.Index(fields=['detected_at'], name='flights_ano_detecte_0654e0_idx'), models.Index(fields=['is_reviewed'], name='flights_ano_is_revi_8fa9c4_idx')],
            },
        ),
    ]
