# Generated by Django 5.2.3 on 2025-11-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-timestamp'], 'permissions': [('can_manage_flight_data', 'Can manage flight data uploads and processing'), ('can_run_ml_operations', 'Can run machine learning operations')]},
        ),
    ]
